/**
 * generated by Xtext 2.34.0-SNAPSHOT
 */
package dsldesign.iupac.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private /* MyDslGrammarAccess */Object _myDslGrammarAccess;

  protected void _format(final /* IUPAC */Object iUPAC, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nchain cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* Chain */Object chain, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nbranch cannot be resolved"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final Object iUPAC, final IFormattableDocument document) {
    if (iUPAC instanceof XtextResource) {
      _format((XtextResource)iUPAC, document);
      return;
    } else if (iUPAC instanceof EObject) {
      _format((EObject)iUPAC, document);
      return;
    } else if (iUPAC == null) {
      _format((Void)null, document);
      return;
    } else if (iUPAC != null) {
      _format(iUPAC, document);
      return;
    } else if (iUPAC != null) {
      _format(iUPAC, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(iUPAC, document).toString());
    }
  }
}
