/*
 * generated by Xtext 2.34.0-SNAPSHOT
 */
package dsldesign.iupac.xtext.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
