/*
 * (c) dsldesign, wasowski, tberger
 generated by Xtext 2.26.0
 */
package dsldesign.iupac.xtext.mydsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
