/*
 * (c) dsldesign, wasowski, tberger
 generated by Xtext 2.26.0
 */
package dsldesign.iupac.xtext.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
