/*
 * generated by Xtext 2.34.0-SNAPSHOT
 */
package dsldesign.iupac.xtext.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
